services:
  public-repo-dashboard:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_VERSION=latest
    container_name: public-repo-dashboard
    environment:
      # This should match the API service URL.
      - PUBLIC_ENDPOINT_URL=https://dashboard.cachyos.org/api
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - cache-data:/app/.next/cache

  cache-cleaner:
    image: alpine:latest
    volumes:
      - cache-data:/app/.next/cache
    entrypoint: |
      sh -c '
        apk add --no-cache supercronic
        echo "0 0 0 * * * * find /app/.next/cache/fetch-cache -type f -atime 1 -delete" > /etc/crontab
        supercronic -debug /etc/crontab
      '

volumes:
  cache-data:
